name: 'Update Trackers List'

on:
  schedule:
    # Runs every Wednesday at 1:00 PM (13:00) UTC
    - cron: '* 13 * * *'

  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  update-trackers-list:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN }}

    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.TOKEN }}

      - name: 'Update packages'
        shell: bash
        run: |
          chmod +x ./scripts/scrape_website
          # TODO: update this later...

      - name: 'Commit new changes'
        shell: bash
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add ./ultimate_trackers.txt
          current_time=$(date +'%Y-%m-%d %H:%M:%S')
          git commit -m "Updated \`ultimate_trackers.txt\` at $current_time"

      - name: 'Push changes'
        uses: 'ad-m/github-push-action@v0.8.0'
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: ${{ github.ref }}
